name: Verify Pull Request Originates from dev Branch

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        run: |
          if [[ "${{ github.event.pull_request.base.ref }}" != "main" ]]; then
            echo "Branch check passed. No action required as the base branch is not 'main'."
            exit 0
          fi
          if [[ "${{ github.head_ref }}" != "dev" ]]; then
          echo "Error: Pull requests to the 'main' branch must originate from the 'dev' branch."
          exit 1
          fi
